AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: crosswordy

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  CrosswordyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Events:
        Discord:
          Type: Api
          Properties:
            Path: /interactions
            Method: post

Outputs:
  CrosswordyApi:
    Description: "API Gateway endpoint URL for Prod stage for Crosswordy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/interactions"
  CrosswordyFunction:
    Description: "Crosswordy Lambda Function ARN"
    Value: !GetAtt CrosswordyFunction.Arn
  CrosswordyFunctionIamRole:
    Description: "Implicit IAM Role created for Crosswordy function"
    Value: !GetAtt CrosswordyFunctionRole.Arn